"""JSONRepair Adapter for Agentium v2.

Repairs malformed, broken, or truncated JSON output generated by LLMs.
"""
from __future__ import annotations

import json
from typing import Any

from .._meta import PACKAGE_NAME

try:
    import json_repair as _raw_jsonrepair
except ImportError:
    try:
        import jsonrepair as _raw_jsonrepair  # type: ignore
    except ImportError:
        _raw_jsonrepair = None  # type: ignore


def _ensure_installed() -> None:
    if _raw_jsonrepair is None:
        raise ImportError(
            f"JSONRepair adapter requires the 'jsonrepair' extra. "
            f"Install via: pip install '{PACKAGE_NAME}[jsonrepair]'"
        )


raw = _raw_jsonrepair


def repair_json(bad_json_string: str) -> str:
    """Repair broken or truncated JSON text and return valid JSON string."""
    _ensure_installed()
    if hasattr(_raw_jsonrepair, "repair_json"):
        return _raw_jsonrepair.repair_json(bad_json_string)
    return _raw_jsonrepair.repair(bad_json_string)


def loads(bad_json_string: str) -> Any:
    """Repair and deserialize broken or truncated JSON text into a Python object."""
    _ensure_installed()
    if hasattr(_raw_jsonrepair, "loads"):
        return _raw_jsonrepair.loads(bad_json_string)
    repaired = repair_json(bad_json_string)
    return json.loads(repaired)
