"""Implementation of 'agentium init' CLI command (F9).

Performs static analysis of project files (NEVER executes user code)
and creates an initial agentium.toml configuration.
"""
from __future__ import annotations

import difflib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple


FRAMEWORK_PATTERNS = {
    "langgraph": [r"\blanggraph\b"],
    "crewai": [r"\bcrewai\b"],
    "openai": [r"\bopenai\b"],
    "google_genai": [r"\bgoogle[._-](?:generativeai|genai)\b", r"\bgemini\b"],
    "langchain": [r"\blangchain\b"],
}


def detect_frameworks(project_root: Path) -> Set[str]:
    """Statically detect frameworks used in project without executing code."""
    detected: Set[str] = set()

    # 1. Check dependency files
    dep_files = [
        project_root / "pyproject.toml",
        project_root / "requirements.txt",
        project_root / "Pipfile",
        project_root / "setup.py",
        project_root / "setup.cfg",
    ]

    for dep_file in dep_files:
        if dep_file.is_file():
            try:
                content = dep_file.read_text(encoding="utf-8", errors="ignore").lower()
                for fw, patterns in FRAMEWORK_PATTERNS.items():
                    for pat in patterns:
                        if re.search(pat, content):
                            detected.add(fw)
            except Exception:
                pass

    # 2. Check imports in top-level or src python files (max depth 3)
    scan_dirs = [project_root, project_root / "src"]
    py_files: List[Path] = []
    for sdir in scan_dirs:
        if sdir.is_dir():
            for root, _, files in os.walk(sdir):
                # Avoid scanning .venv, node_modules, .git
                if any(ignored in root for ignored in [".venv", "venv", ".git", "__pycache__", "node_modules", "build", "dist"]):
                    continue
                for f in files:
                    if f.endswith(".py"):
                        py_files.append(Path(root) / f)
                        if len(py_files) >= 50:  # limit scan
                            break
                if len(py_files) >= 50:
                    break

    for py_file in py_files:
        try:
            content = py_file.read_text(encoding="utf-8", errors="ignore")
            for fw, patterns in FRAMEWORK_PATTERNS.items():
                if fw in detected:
                    continue
                for pat in patterns:
                    if re.search(r"^\s*(?:import|from)\s+" + pat, content, re.MULTILINE):
                        detected.add(fw)
        except Exception:
            pass

    return detected


def generate_config_content(detected_frameworks: Set[str]) -> str:
    """Generate agentium.toml content based on detected frameworks."""
    lines = [
        "# Agentium v2 Configuration",
        "# Generated by 'agentium init'",
        "",
        "[events]",
        'dir = ".agentium/events"',
        "enabled = true",
        "",
        "[redact]",
        "enabled = true",
        "redact_keys = true",
        "redact_emails = true",
        "",
        "[fingerprint]",
        'ignore = ["$.params.seed"]',
        "normalize_whitespace = false",
        "redact_before_hash = true",
        "",
        "[gate]",
        'mode = "shadow"  # options: "shadow", "enforce"',
        "",
        "[adapters]",
    ]

    if "langgraph" in detected_frameworks:
        lines.append('langgraph = { enabled = true }')
    else:
        lines.append('# langgraph = { enabled = false }')

    if "crewai" in detected_frameworks:
        lines.append('crewai = { enabled = true }')
    else:
        lines.append('# crewai = { enabled = false }')

    if "openai" in detected_frameworks:
        lines.append('openai_agents = { enabled = true }')
    else:
        lines.append('# openai_agents = { enabled = false }')

    lines.append("")
    return "\n".join(lines)


def run_init(
    project_root: Path,
    dry_run: bool = False,
    force: bool = False,
    as_json: bool = False,
) -> Tuple[int, str]:
    """Execute init logic. Returns (exit_code, output_message)."""
    target_path = project_root / "agentium.toml"
    detected = detect_frameworks(project_root)
    proposed_content = generate_config_content(detected)

    if target_path.exists() and not force and not dry_run:
        msg = f"Configuration file already exists at '{target_path}'. Use --force to overwrite."
        if as_json:
            return 1, json.dumps({"status": "error", "error": msg})
        return 1, f"Error: {msg}\n"

    if dry_run:
        existing_lines = []
        if target_path.exists():
            existing_lines = target_path.read_text(encoding="utf-8").splitlines(keepends=True)
        proposed_lines = proposed_content.splitlines(keepends=True)

        diff = list(
            difflib.unified_diff(
                existing_lines,
                proposed_lines,
                fromfile=str(target_path) if target_path.exists() else "/dev/null",
                tofile=str(target_path),
            )
        )
        diff_text = "".join(diff) if diff else "(No changes)\n"

        if as_json:
            return 0, json.dumps({
                "status": "dry-run",
                "detected_frameworks": sorted(list(detected)),
                "diff": diff_text,
                "proposed_content": proposed_content,
            })
        return 0, f"Detected frameworks: {', '.join(sorted(detected)) or 'none'}\nProposed agentium.toml diff:\n{diff_text}"

    # Write file
    target_path.write_text(proposed_content, encoding="utf-8")

    # Also ensure .agentium/events exists
    events_dir = project_root / ".agentium" / "events"
    events_dir.mkdir(parents=True, exist_ok=True)

    if as_json:
        return 0, json.dumps({
            "status": "ok",
            "file": str(target_path),
            "detected_frameworks": sorted(list(detected)),
        })
    return 0, f"Initialized Agentium configuration at '{target_path}'.\nDetected frameworks: {', '.join(sorted(detected)) or 'none'}\n"
